@baseUrl = http://localhost:8080
@bookId = 3

### Create book
POST {{baseUrl}}/books
Content-Type: application/json

{
  "title": "吾輩は猫である",
  "price": 1200,
  "authorIds": [1],
  "publicationStatus": "PUBLISHED"
}

### Update book authors
PATCH {{baseUrl}}/books/{{bookId}}
Content-Type: application/json

{
  "authorIds": [2]
}

### Update book price and authors
PATCH {{baseUrl}}/books/{{bookId}}
Content-Type: application/json

{
  "price": 1500,
  "authorIds": [86, 87, 88]
}

### Create book fails when price is negative
POST {{baseUrl}}/books
Content-Type: application/json

{
  "title": "吾輩は猫である",
  "price": -1,
  "authorIds": [56],
  "publicationStatus": "PUBLISHED"
}

### Create book fails when authorIds is empty
POST {{baseUrl}}/books
Content-Type: application/json

{
  "title": "吾輩は猫である",
  "price": 1200,
  "authorIds": [],
  "publicationStatus": "PUBLISHED"
}

### Create book fails when author does not exist
POST {{baseUrl}}/books
Content-Type: application/json

{
  "title": "吾輩は猫である",
  "price": 1200,
  "authorIds": [999999],
  "publicationStatus": "PUBLISHED"
}
